import { Button, VerticalBox, HorizontalBox, SpinBox } from "std-widgets.slint";
import { PaintCanvas } from "paint_canvas.slint";
import { Palette } from "std-widgets.slint";

export component PaintWindow inherits Window {
  in property <image> canvas_background <=> canvas.canvas_background;
  in property <image> canvas_source <=> canvas.canvas;
  in property <image> canvas_preview <=> canvas.canvas_preview;
  in-out property canvas_width <=> canvas.width;
  in-out property canvas_height <=> canvas.height;
  out property <int> brush_value <=> brush_box.value;
  private property <bool> ctrl_pressed;
  callback mouse_event(PointerEvent, length, length, bool);
  callback spin_box_edited(int);
  callback select_freehand();
  callback select_line();
  callback select_rect();
  callback select_circle();
  callback clear();

    VerticalBox {
      HorizontalBox {
        height: 40pt;
        btn_freehand := Button {
          checked: true;
          checkable: true;
          text: "Freehand";
          clicked => {
            if (self.checked) {
              btn_line.checked = false;
              btn_rect.checked = false;
              btn_circle.checked = false;
              root.select_freehand();
            } else {
              self.checked = true;
            }
          }
        }
        btn_line := Button {
          checkable: true;
          text: "Line";
          clicked => {
            if (self.checked) {
              btn_freehand.checked = false;
              btn_rect.checked = false;
              btn_circle.checked = false;
              root.select_line();
            } else {
              self.checked = true;
            }
          }
        }
        btn_rect := Button {
          checkable: true;
          text: "Rectangle";
          clicked => {
            if (self.checked) {
              btn_freehand.checked = false;
              btn_line.checked = false;
              btn_circle.checked = false;
              root.select_rect();
            } else {
              self.checked = true;
            }
          }
        }
        btn_circle := Button {
          checkable: true;
          text: "Ellipse";
          clicked => {
            if (self.checked) {
              btn_freehand.checked = false;
              btn_line.checked = false;
              btn_rect.checked = false;
              root.select_circle();
            } else {
              self.checked = true;
            }
          }
        }
        brush_box := SpinBox {
          minimum: 1.0;
          maximum: 20.0;
          value: 5.0;

          edited(value) => {
            root.spin_box_edited(value);
          }
        }

        Button {
          text: "Clear";
          clicked => {
            root.clear();
          }
        }
      }
      canvas := PaintCanvas {
        pointer-event(PointerEvent) => {
          root.mouse_event(PointerEvent, self.mouse-x, self.mouse-y, self.pressed)
        }
      }
    }
  }

